
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="costumes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Costumes" #mandatory

logoFile="logo.png" #optional
authors="RedRoseWarrior1" #optional
description='''More 10 amazing armors'''
[[dependencies.costumes]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.costumes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
